---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: jhdc-72
    driver_config:
      customize:
        cpus: 2
        memory: 1024

suites:
  - name: default
    data_bags_path: ../jhdc-data/data_bags/
    run_list:
      - recipe[jhdc-web::default]
    attributes:
  - name: puka
    data_bags_path: ../jhdc-data/data_bags/
    run_list:
      - recipe[jhdc-web::puka]
    attributes:
