driver:
  name: digitalocean
  image: centos-7-0-x64
  private_networking: false
  size: 1gb

transport:
  name: rsync

suites:
  - name: default
    data_bags_path: ../jhdc-data/data_bags/
    run_list:
      - recipe[jhdc-web::default]
    attributes:
      nginx:
        cert: 'sodium.jeffhutchison.com'
        alt_certs:
          - 'www.jeffhutchison.com'
          - 'potassium.jeffhutchison.com'
