name             'jhdc-web'
maintainer       'Jeff Hutchison'
maintainer_email 'jeff@jeffhutchison.com'
license          'All rights reserved'
description      'Installs/Configures web services'
long_description 'Installs/Configures web services'
version          '0.6.0'
supports         'centos'

depends 'build-essential'
depends 'yum-epel'
depends 'firewalld'
depends 'users'
depends 'letsencrypt'
